/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as InscripcionRouteImport } from './routes/inscripcion'
import { Route as EncuestaRouteImport } from './routes/encuesta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedMisTalleresRouteImport } from './routes/_authenticated/mis-talleres'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionRoute = InscripcionRouteImport.update({
  id: '/inscripcion',
  path: '/inscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuestaRoute = EncuestaRouteImport.update({
  id: '/encuesta',
  path: '/encuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisTalleresRoute =
  AuthenticatedMisTalleresRouteImport.update({
    id: '/mis-talleres',
    path: '/mis-talleres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/encuesta': typeof EncuestaRoute
  '/inscripcion': typeof InscripcionRoute
  '/talleres': typeof TalleresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/mis-talleres': typeof AuthenticatedMisTalleresRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/encuesta': typeof EncuestaRoute
  '/inscripcion': typeof InscripcionRoute
  '/talleres': typeof TalleresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/mis-talleres': typeof AuthenticatedMisTalleresRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/encuesta': typeof EncuestaRoute
  '/inscripcion': typeof InscripcionRoute
  '/talleres': typeof TalleresRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/mis-talleres': typeof AuthenticatedMisTalleresRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/encuesta'
    | '/inscripcion'
    | '/talleres'
    | '/admin'
    | '/empresa'
    | '/mis-talleres'
    | '/oportunidades'
    | '/panel'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/encuesta'
    | '/inscripcion'
    | '/talleres'
    | '/admin'
    | '/empresa'
    | '/mis-talleres'
    | '/oportunidades'
    | '/panel'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/encuesta'
    | '/inscripcion'
    | '/talleres'
    | '/_authenticated/admin'
    | '/_authenticated/empresa'
    | '/_authenticated/mis-talleres'
    | '/_authenticated/oportunidades'
    | '/_authenticated/panel'
    | '/_authenticated/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EncuestaRoute: typeof EncuestaRoute
  InscripcionRoute: typeof InscripcionRoute
  TalleresRoute: typeof TalleresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion': {
      id: '/inscripcion'
      path: '/inscripcion'
      fullPath: '/inscripcion'
      preLoaderRoute: typeof InscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encuesta': {
      id: '/encuesta'
      path: '/encuesta'
      fullPath: '/encuesta'
      preLoaderRoute: typeof EncuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-talleres': {
      id: '/_authenticated/mis-talleres'
      path: '/mis-talleres'
      fullPath: '/mis-talleres'
      preLoaderRoute: typeof AuthenticatedMisTalleresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedMisTalleresRoute: typeof AuthenticatedMisTalleresRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedMisTalleresRoute: AuthenticatedMisTalleresRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EncuestaRoute: EncuestaRoute,
  InscripcionRoute: InscripcionRoute,
  TalleresRoute: TalleresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
